### PR TITLE
Adjust solution to support multiple projects

### PR DESCRIPTION
**Pull request by dlamli**

### CODE REVIEW

**Review by Gabuardi — COMMENTED** [review]
All the Git file must to be on `root` of the repository... also check creating and running a new project on the solution

**Comment by dlamli** [comment]
> All the Git file must to be on `root` of the repository... also check creating and running a new project on the solution

I already test it and its working correctly.

**Review by Gabuardi — COMMENTED** [review]
Move the README.md as well

**Comment by dlamli** [comment]
> Move the README.md as well

Done.

**Review by Gabuardi — APPROVED** [review]

**Pull request merged**
